package stockanalysis

import (
	"encoding/json"
)

func NeedsResearchRevalidation(report *ResearchReport) bool {
	return report != nil && (report.PromptVersion == "stock-research-v7" || report.PromptVersion == "stock-research-v8" || report.PromptVersion == "stock-research-v9" || report.PromptVersion == ResearchPromptVersion) && report.ValidationVersion != ResearchValidationVersion
}

// Replay only the original successful model outputs against their frozen
// snapshot. Never upgrade a persisted insufficient judgment by guessing what
// the model meant, fetch new facts, renew the 24h window, or overwrite history.
func RevalidateReusableResearch(job ResearchJob) ResearchJob {
	if !SuccessfulResearch(job) || !NeedsResearchRevalidation(job.Analysis.ResearchReport) || job.Snapshot == nil || job.Checkpoint == nil {
		return job
	}
	cp := job.Checkpoint
	if cp.PromptVersion != job.Analysis.ResearchReport.PromptVersion || cp.SnapshotHash != researchHash(job.Snapshot) || researchHash(cp.Request) != researchHash(job.Request) {
		return job
	}
	encoded, err := json.Marshal(job)
	if err != nil {
		return job
	}
	var copy ResearchJob
	if json.Unmarshal(encoded, &copy) != nil {
		return job
	}
	var result ResearchSynthesis
	if output, ok := copy.Checkpoint.Outputs["研究结构修复"]; ok {
		if json.Unmarshal(output.Value, &result) != nil {
			return job
		}
	} else {
		coreOutput, coreOK := copy.Checkpoint.Outputs["核心判断"]
		tradeOutput, tradeOK := copy.Checkpoint.Outputs["交易条件"]
		if !coreOK || !tradeOK {
			return job
		}
		var core ResearchCoreSynthesis
		var trade ResearchTradeConditions
		if json.Unmarshal(coreOutput.Value, &core) != nil || json.Unmarshal(tradeOutput.Value, &trade) != nil {
			return job
		}
		result = ResearchSynthesis{TradingLogic: core.TradingLogic, Headline: core.Headline, Thesis: core.Thesis, Support: core.Support, Counter: core.Counter, Alternatives: core.Alternatives, MainConflict: core.MainConflict, EvidenceLevel: core.EvidenceLevel, Limitations: core.Limitations, BaselineRelation: core.BaselineRelation, BaselineReason: core.BaselineReason, Conditions: trade.Conditions, InvalidationIDs: trade.InvalidationIDs, Scenarios: trade.Scenarios, Decision: trade.Decision}
	}
	// Remove only the obsolete limitation generated by the old validator.
	limitations := []string{}
	for _, value := range copy.Snapshot.Limitations {
		if value != "日线距分析时点超过5天，行情可能过期或停牌，禁止生成新仓价格计划" {
			limitations = append(limitations, value)
		}
	}
	copy.Snapshot.Limitations = limitations
	if researchPricesStale(*copy.Snapshot) {
		copy.Snapshot.Limitations = append(copy.Snapshot.Limitations, researchPriceFreshnessReason(*copy.Snapshot))
	}
	notes, err := validateRequestedResearch(&result, *copy.Snapshot, copy.Request)
	if err != nil {
		return job
	}
	report := *copy.Analysis.ResearchReport
	report.ResearchSynthesis = result
	report.ValidationVersion = ResearchValidationVersion
	report.ValidationNotes = append(notes, "复用原模型输出，按交易日、来源内容、分离的证据/交易校验及可选价格计划重新检查；未调用AI、未补充新资料，原报告完成时点不变")
	ApplyResearch(copy.Analysis, &report, *copy.Snapshot)
	// Keep the snapshot immutable for any later persistence by callers.
	copy.Snapshot = job.Snapshot
	return copy
}
